### ISSUE TITLE
Incorrect assertion

### ISSUE THREAD

**Issue by Ariestattoo** [DCzajkowski/auth-tests#11]
Thanks for putting this together. saved me a lot of time.
### Environment
- Laravel Version: 5.7.

- PHP Version: PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 09:55:44) ( NTS )

### Description:
testUserCannotVereifyOthers() fails on a correct redirect assertion

### Steps To Reproduce:
```
 public function testUserCannotVerifyOthers()
    {
        $user = factory(User::class)->create([
            'id' => 1,
            'email_verified_at' => null,
        ]);

        $response = $this->actingAs($user)->get($this->validVerificationVerifyRoute(2));
        $response->assertRedirect($this->successfulVerificationRoute());
        // Should be ???
        // $response->assertForbidden();
    }
```

**Comment by DCzajkowski** [comment]
Thank you for reporting. Fixed in [5.7.14](https://github.com/DCzajkowski/auth-tests/releases/tag/5.7.14). It's weird, because all of the tests were passing when I last checked. Will investigate!

**Comment by DCzajkowski** [comment]
Ok, so I've checked, and the previous version worked on 5.7.0. It seems like Laravel fixed an issue, hence the breaking change

**Comment by DCzajkowski** [comment]
Exactly what I expected. Since Laravel 5.7.14 tests haven't been passing because this is where the change was introduced: https://github.com/laravel/framework/pull/26528. It seems like during writing the tests I haven't noticed, whoops 🙈

**Comment by DCzajkowski** [comment]
Whoops, 5.7.14 is the newest release that should be installed 😉

**Comment by Ariestattoo** [comment]
Awesome!!. Thanks for all your hard work

**Comment by DCzajkowski** [comment]
No problem :) Glad it helped someone 😉

**Comment by flick36** [comment]
Apparently there was another change, because Remember Me functionality test isn't passing anymore

**Comment by DCzajkowski** [comment]
Hey @flick36. I have confirmed, and using Laravel 5.8.7 and auth-tests 5.8 work as expected.

![](https://i.imgur.com/IW7dOEa.png)

If something is not working for you, please create a new issue explaining the problem in more detail.
