### ISSUE TITLE
Remember Me won't work when Invalidating Sessions On Other Devices

### ISSUE THREAD

**Issue by flick36** [DCzajkowski/auth-tests#16]
### Environment
- Laravel Version: 5.8.7
- PHP Version: 7.3

### Description:
For starters there's no test for [Invalidating Sessions On Other Devices](https://laravel.com/docs/5.8/authentication#logging-out) and since that changes the password hash on the cookie, the remember me test becomes a failing test.

Also, we shouldn't be using the bcrypt helper anymore, since i think argon2id will become the default once php 7.1 is no longer supported, which should be this December.

### Steps To Reproduce:
1.- Fresh Laravel Install
2.- Add [Invalidating Sessions On Other Devices](https://laravel.com/docs/5.8/authentication#logging-out) Functionality
3.- Test

**Comment by DCzajkowski** [comment]
Great! Thank you for this detailed information. I will investigate soon!

**Comment by DCzajkowski** [comment]
Hey, I have went through your reproduction steps and everything works as expected. I am running Laravel 5.8.8.
As far as I can see, `AuthenticateSession` does not change the _remember me_ cookie, but takes values out of it to compare with a value in the session.

Here is a repository with everything working as expected: https://github.com/DCzajkowski/auth-tests-demo. You can look at individual commits to see what has changed.

I will close this for now. If you think it's a mistake, feel free to open it back 😉

**Comment by flick36** [comment]
Yeah, you forgot to actually use it, in the login controller: 

`
use Illuminate\Support\Facades\Auth;
`

and in the authenticated method
```
/**
 * The user has been authenticated.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  mixed  $user
 * @return mixed
 */
public function authenticated(Request $request, $user)
{
    Auth::logoutOtherDevices($request->password);
}
``` 
Supporting video demonstrating the Hash changue 
[Laracasts](https://laracasts.com/series/whats-new-in-laravel-5-6/episodes/7)

**Comment by DCzajkowski** [comment]
I have made a new release [5.8.1](https://github.com/DCzajkowski/auth-tests/releases/tag/5.8.1) with this commit specifically https://github.com/DCzajkowski/auth-tests/commit/0ebbb93a3b28f22ef995683d0d5786b34a8dcec4
