### ISSUE TITLE
Update auth tests to be used on laravel 5.9

### ISSUE THREAD

**Issue by guifabrin** [DCzajkowski/auth-tests#17]
### Environment
- Laravel Version: 5.9.1
- PHP Version: 7.2

### Description:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laravel/framework 5.9.* is satisfiable by laravel/framework[5.9.x-dev] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package laravel/framework (locked at v5.8.13, required as 5.9.*) is satisfiable by laravel/framework[v5.8.13] but these conflict with your requirements or minimum-stability.
  Problem 3
    - dczajkowski/auth-tests 5.8.1 requires laravel/framework ~5.8 -> satisfiable by laravel/framework[5.8.x-dev, 5.9.x-dev, v5.8.0, v5.8.1, v5.8.10, v5.8.11, v5.8.12, v5.8.13, v5.8.2, v5.8.3, v5.8.4, v5.8.5, v5.8.6, v5.8.7, v5.8.8, v5.8.9] but these conflict with your requirements or minimum-stability.
    - dczajkowski/auth-tests 5.8 requires laravel/framework ~5.8 -> satisfiable by laravel/framework[5.8.x-dev, 5.9.x-dev, v5.8.0, v5.8.1, v5.8.10, v5.8.11, v5.8.12, v5.8.13, v5.8.2, v5.8.3, v5.8.4, v5.8.5, v5.8.6, v5.8.7, v5.8.8, v5.8.9] but these conflict with your requirements or minimum-stability.
    - Installation request for dczajkowski/auth-tests ^5.8 -> satisfiable by dczajkowski/auth-tests[5.8, 5.8.1].

**Comment by DCzajkowski** [comment]
Hey @guifabrin. Laravel 5.9 is not out yet and there is no official upgrade guide available. I do not know what breaking changes are there going to be, so I cannot make the package available for 5.9 quite yet. If you want, you can try to run the `auth:make-tests` command on the 5.8 release and then upgrade to 5.9. But I cannot promise it will work with the new release.

**Comment by guifabrin** [comment]
Hi @DCzajkowski thanks for reply, you are right. Actually I was testing a bug on a client laravel site where when one user logon as same time another user in another session and sessions are "mixing". But I downgrade laravel to 5.8.9 and works perfectly.

Thanks for awesome code.
