### ISSUE TITLE
Make testUserCannotMakeMoreThanFiveAttemptsInOneMinute Language agnostic

### ISSUE THREAD

**Issue by jhm-ciberman** [DCzajkowski/auth-tests#18]
I want to suggest a small recomendation. My app is in spanish, so the texts are in spanish and the fallback locale is in english. So, the LoginTest natuarally fails:

```
There was 1 failure:

1) Tests\Feature\Auth\LoginTest::testUserCannotMakeMoreThanFiveAttemptsInOneMinute
Failed asserting that 'Demasiados intentos de acceso. Por favor intente nuevamente en 60 segundos.' contains "Too many login attempts.".

/home/vagrant/code/ce/tests/Feature/Auth/LoginTest.php:174
```

It can easily be solved forcing the app to be in english before executing the tests :) 

```
    public function testUserCannotMakeMoreThanFiveAttemptsInOneMinute()
    {
        $this->app->setLocale('en');
        // ...
```

By the way, amazing package. I love it!

**Comment by DCzajkowski** [comment]
Thanks for reporting. I tried to make all tests language-agnostic but this one slipped. I have released [a new version with the change](https://github.com/DCzajkowski/auth-tests/releases/tag/5.8.2).
