### ISSUE TITLE
Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9

### ISSUE THREAD

**Issue by jhm-ciberman** [DCzajkowski/auth-tests#19]
### Environment
- Laravel Version: 5.8.17
- PHP Version: 7.3.1
- PHPUnit Version: 8.1.5

### Description:
```

There was 1 warning:

1) Tests\Feature\Auth\LoginTest::testUserCannotMakeMoreThanFiveAttemptsInOneMinute
Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStr
ingIgnoringCase() instead.

```

### Steps To Reproduce:
Simply run the tests

**Comment by DCzajkowski** [comment]
Thanks for reporting. Even though version 8 of phpunit is not officially in Laravel quite yet, I have updated the test and made [a new release](https://github.com/DCzajkowski/auth-tests/releases/tag/5.8.2).
