### ISSUE TITLE
Random failed test results 

### ISSUE THREAD

**Issue by Snaver** [DCzajkowski/auth-tests#4]
Getting some really weird issues with this.. My test results are failing randomly. Sometimes none fail, sometimes two.. sometimes three? Examples:

```
1) Tests\Feature\Auth\ForgotPasswordTest::testUserReceivesAnEmailWithAPasswordResetLink
Failed asserting that null is not null.

..xxx/tests/Feature/Auth/ForgotPasswordTest.php:66
```

```
2) Tests\Feature\Auth\LoginTest::testUserCanLoginWithCorrectCredentials
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://localhost/dashboard'
+'http://localhost'

...xxx/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:96
...xxx/tests/Feature/Auth/LoginTest.php:72
```
Note my home is really 'dashboard' now, dashboard is behind auth (part of web,auth middleware) - could this be it?

Any ideas?

**Comment by DCzajkowski** [comment]
Are you sure you have the default `password_resets` table?

The second fail is because of that route. Simply change the `successfulLoginRoute()` method in `LoginTest` to be the one you use.

**Comment by DCzajkowski** [comment]
Also, as for the second fail, can you try changing:
```php
// change this
$response = $this->post($this->loginPostRoute(), [
// to this
$response = $this->fromPage($this->loginGetRoute())->post($this->loginPostRoute(), [
```
and see what happens.

**Comment by DCzajkowski** [comment]
Also, can you please provide what Laravel version are you using?

**Comment by Snaver** [comment]
Ah bugger, this is my bad... I had modified my UserFactory to randomly mark some users as deleted (Since I was testing this functionality in my app). This explains why I was seeing different test results on each separate run.

Fix for me is to either stop marking random users as deleted in my UserFactory or ensure users are active when using a factory in a test:

```
$user = factory(User::class)->create([
    'password' => bcrypt($password = 'i-love-laravel'),
    'deleted_at' => null,
]);
```

Laravel 5.5 FYI..

Sorry for wasting your time @DCzajkowski !

**Comment by DCzajkowski** [comment]
No worries :) Awesome you have resolved your issue. Good luck :D
