### ISSUE TITLE
assertRegExp() is deprecated and will be removed in PHPUnit 10

### ISSUE THREAD

**Issue by ragulka** [DCzajkowski/auth-tests#51]
### Environment
- Laravel Version: 7.15.0
- PHP Version: 7.4.5

### Description:

When running the `testUserCannotMakeMoreThanFiveAttemptsInOneMinute` test, I see the following deprecation warning:

```
assertRegExp() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertMatchesRegularExpression() instead
```

**Comment by DCzajkowski** [comment]
Thanks for the heads up! You can make a PR or I will update it in the upcoming days 😉

**Comment by DCzajkowski** [comment]
The problem is Laravel 7.x [uses phpunit 8.x by default](https://github.com/laravel/laravel/blob/fa43c0a333d623a393fa33c27a1376f69ef3f301/composer.json#L23), and phpunit 8 does not have this method yet. I will wait with #53 until Laravel upgrades to 9 or 10.

**Comment by drbyte** [comment]
FYI: It was [phpUnit 9.1](https://phpunit.readthedocs.io/en/9.1/assertions.html#assertmatchesregularexpression) where `assertRegExp` was replaced by `assertMatchesRegularExpression`

**Comment by DCzajkowski** [comment]
Good to know @drbyte, thanks!
