### ISSUE TITLE
PasswordReset issue

### ISSUE THREAD

**Issue by DWMcload** [DCzajkowski/auth-tests#61]
### Environment
- Laravel Version: 5.8.38
- PHP Version: 7.3.10

### Description:
I know I'm using an old laravel, this is a legacy project. 
I've used this package previously and I found it really pleasurable.
Now I have an issue which bugs me for hours now and maybe you have an idea. 

1) Tests\Feature\Auth\ForgotPasswordTest::testUserReceivesAnEmailWithAPasswordResetLink
Failed asserting that null is not null.
This code snippet:
 
```php
$user = factory(User::class)->create([
    'email' => 'john@example.com',
]);
$this->post($this->passwordEmailPostRoute(), [
    'email' => 'john@example.com',
]);
$this->assertNotNull($token = DB::table('password_resets')->first());
```

### Steps To Reproduce:
The user gets written into the database, but for some reason, the provider can't return it, it always fetches null. 
I dumped the data, the queries, everything seems to be fine, still, always null. Any idea?

Thank you!

**Comment by DCzajkowski** [comment]
For some reason, a token is not being added to the `password_resets` table.

1. What version of the package are you using?
1. Have you by any chance changed the name of the password resets table?
1. Can you see what the response is?

```php
$this->withoutExceptionHandling();

$response = $this->post($this->passwordEmailPostRoute(), [
    'email' => 'john@example.com',
]);

dd($response);
```

4. What is `$this->passwordEmailPostRoute()` returning? Is the route correct?

**Comment by DWMcload** [comment]
1. It's the same 5.8 as the laravel version. I'm fairly sure the issue is not in your package, I just would like to understand why this is happening and couldn't find many better places to ask (posted on SO as well... ) so I very much appreciate your time and ideas trying to help me. 
2. No, no change. The code doesn't go that far to write into that table yet. 
3. it says the following:
1) Tests\Feature\Auth\ForgotPasswordTest::testUserReceivesAnEmailWithAPasswordResetLink
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'web' not found

/Users/mcload/Sites/weframe/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/MorphTo.php:156

**Maybe that is my problem?** I'm starting to investigate and fix this. 

4. It returns 'password.email' It goes to the correct place in src/Illuminate/Routing/Router.php as by default should.
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');

**Comment by DWMcload** [comment]
Thank you @DCzajkowski so much! The error message I could see with $this->withoutExceptionHandling(); solved my issue, my User factory created invalid values, making it impossible to return the user. I once again really appreciate your time and help. 
_Polak wegier dwa bratanki, I do slabki I do bratki._

**Comment by DCzajkowski** [comment]
No problem. I am glad I could have been of help.

I am going to close this issue, but feel welcomed to open a new one should any problems arise.

_Lengyel, magyar két jó barát, együtt harcol, s issza borát_
