### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by clarkeash** [DCzajkowski/auth-tests#7]
### Environment
- Laravel Version: 5.6
- PHP Version: 7

### Description:

Can we get a release for laravel 5.6?

When installing in a laravel 5.6 project composer pulls in version 5.5.4 of your lib, which doesnt have all the flags.

**Comment by DCzajkowski** [comment]
Oh, interesting. I'll have a look at it ASAP

**Comment by DCzajkowski** [comment]
a3e4f56 fixes this. I am sorry for inconvenience and thank you for good call 👍
