### ISSUE TITLE
Testing "remember me" functionality?

### ISSUE THREAD

**Issue by ghost** [DCzajkowski/auth-tests#8]
### Environment
- Laravel Version: 5.6.16
- PHP Version: 7.2

### Description:
Any plans to add tests for "remember me" functionality?

### Steps To Reproduce:
None

**Comment by DCzajkowski** [comment]
Absolutely! I have forgotten about that flow of the authentication. If you want, you can make a PR with a feature, or I can do it, but in a few days. This weekend I won't have time unfortunately.

**Comment by ghost** [comment]
I'm afraid I'm no help here, sadly. All this is pretty new to me.

**Comment by DCzajkowski** [comment]
Ok, no worries! I'll take care of it as soon as I have more time on my hands ;)

**Comment by ghost** [comment]
Yeah, no hurry :) And thank you for your time!

**Comment by DCzajkowski** [comment]
Hey. As an update, a new 5.6.2 version of the package has been released ;) 
Happy Coding!
